import { expect, test } from '@playwright/test'

const password = 'correct horse battery staple'

test('generic inventory workflow supports duplicate copies and location states', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Username').fill('adminuser')
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByLabel('Open application menu')).toBeVisible()
  await page.goto('/collections')
  await page.getByRole('link', { name: 'Browser collection' }).click()
  const collectionPath = new URL(page.url()).pathname
  const collectionId = collectionPath.split('/').at(-2)

  await page.goto(`/collections/${collectionId}/inventory`)
  const collectionNavigation = page.getByLabel('Collection navigation')
  await expect(collectionNavigation.getByRole('link')).toHaveText(['Inventory', 'Locations', 'Settings', 'Add item'])
  await collectionNavigation.getByRole('link', { name: 'Settings' }).click()
  await page.getByRole('button', { name: 'Advanced' }).click()
  await page.getByRole('link', { name: 'Open advanced catalog' }).click()
  await expect(page.getByRole('heading', { name: 'Advanced catalog' })).toBeVisible()
  await expect(page.getByText('Low-level access to title, edition and identifier records.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'Back to Settings' })).toBeVisible()
  await page.goto(`/collections/${collectionId}/inventory`)
  await page.getByRole('link', { name: 'Add item' }).click()
  await page.getByLabel('Title').fill('T06 Browser Title')
  await page.getByRole('button', { name: 'Create new title "T06 Browser Title"' }).click()
  await page.getByLabel('Edition').selectOption('Steelbook')
  await page.getByLabel('Media format').selectOption('Blu-ray')
  await page.getByLabel('Publisher / distributor').selectOption('Warner Bros. Home Entertainment')
  await page.getByRole('checkbox', { name: 'Region B' }).check()
  await page.getByRole('checkbox', { name: 'German' }).check()
  await page.getByRole('checkbox', { name: 'English' }).check()
  await page.getByLabel('Condition').selectOption('Sealed')
  await page.getByLabel('Location').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Add item' }).click()
  await expect(page.getByRole('heading', { name: 'T06 Browser Title' })).toBeVisible()
  await expect(page.getByText('Steelbook', { exact: true })).toBeVisible()
  await expect(page.getByText('Blu-ray', { exact: true })).toBeVisible()
  await expect(page.getByText('Warner Bros. Home Entertainment', { exact: true })).toBeVisible()
  await expect(page.locator('.edition-detail-card__metadata')).toContainText('Region B')
  await expect(page.locator('.edition-detail-card__metadata')).toContainText('German · English')
  await expect(page.getByText('Sealed', { exact: true })).toBeVisible()
  await expect(page.getByText('Archive Box', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Add edition' }).click()
  await page.getByLabel('Edition', { exact: true }).selectOption('__custom__')
  await page.getByLabel('Other / Custom Edition').fill('Limited Edition')
  await page.getByLabel('Media format').selectOption('UHD Blu-ray')
  await page.getByRole('checkbox', { name: 'Region Free' }).check()
  await page.getByRole('checkbox', { name: 'English' }).check()
  await page.getByLabel('Condition').selectOption('Mint')
  await page.locator('form select').last().selectOption({ index: 1 })
  await page.locator('form textarea').fill('First limited copy')
  await page.getByRole('button', { name: 'Add edition & copy' }).click()
  const limitedEdition = page.locator('.edition-detail-card').filter({ hasText: 'Limited Edition' })
  await expect(limitedEdition).toContainText('UHD Blu-ray')
  await expect(limitedEdition).toContainText('Copy 1')
  await limitedEdition.getByRole('link', { name: 'Add physical copy' }).click()
  await page.getByLabel('Condition').selectOption('Sealed')
  await page.getByRole('button', { name: 'Add physical copy' }).click()
  await expect(limitedEdition.locator('.copy-read-card')).toHaveCount(2)
  await page.setViewportSize({ width: 375, height: 800 })
  await expect(page.getByText('Steelbook', { exact: true })).toBeVisible()
  expect(await page.locator('body').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.getByRole('link', { name: 'Back to Inventory' }).click()
  await page.getByRole('link', { name: 'Add item' }).click()
  await page.getByLabel('Title').fill('T06 Browser Title')
  await expect(page.getByRole('button', { name: 'Use existing' })).toBeVisible()
  await page.getByRole('button', { name: 'Use existing' }).click()
  await page.getByRole('button', { name: 'Use this edition' }).first().click()
  await page.getByRole('button', { name: 'Add item' }).click()
  await page.getByRole('link', { name: 'Back to Inventory' }).click()
  const titleCard = page.locator('.library-card').filter({ hasText: 'T06 Browser Title' })
  await expect(titleCard).toHaveCount(1)
  await expect(titleCard).toContainText('2 editions · 4 copies')
  await expect(page.locator('.filter-toolbar__summary')).toContainText('1 title · 4 physical copies')
  await titleCard.getByRole('link', { name: 'Open T06 Browser Title' }).click()

  const firstCopy = page.locator('.edition-detail-card').filter({ hasText: 'Steelbook' }).locator('.copy-read-card').filter({ hasText: 'Copy 1' })
  await firstCopy.getByRole('link', { name: 'Edit copy' }).click()
  await expect(page.getByRole('heading', { name: 'Copy 1' })).toBeVisible()
  await page.getByLabel('Condition').selectOption('Very Good')
  await page.locator('.collection-form textarea').fill('Browser-managed copy')
  await page.getByRole('button', { name: 'Save copy' }).click()
  await expect(page.getByText('Very Good')).toBeVisible()
  await expect(page.getByText('Browser-managed copy')).toBeVisible()

  await firstCopy.getByRole('link', { name: 'Edit copy' }).click()
  await page.getByRole('button', { name: 'Location' }).click()
  const currentLocation = page.locator('.copy-location-management__current')
  await expect(currentLocation).toContainText('Archive Box')
  await page.getByLabel('Move / Assign location').selectOption({ index: 2 })
  await page.getByRole('button', { name: 'Move copy' }).click()
  await expect(currentLocation).not.toContainText('Unassigned')
  await page.getByRole('button', { name: 'Remove from location' }).click()
  await expect(currentLocation).toContainText('Unassigned')
  await page.getByRole('link', { name: 'Back to title' }).click()
  const steelbookEdition = page.locator('.edition-detail-card').filter({ hasText: 'Steelbook' })
  await steelbookEdition.getByRole('link', { name: 'Edit edition' }).click()
  await page.getByRole('button', { name: 'Barcodes & IDs' }).click()
  await page.getByRole('button', { name: 'Add barcode or ID' }).click()
  await page.getByLabel('Barcode / ID').fill('5053083188269')
  await expect(page.getByText('Detected type: EAN-13')).toBeVisible()
  await page.getByRole('button', { name: 'Add barcode / ID' }).click()
  await expect(page.getByText('EAN-13', { exact: true })).toBeVisible()
  await expect(page.getByText('5053083188269', { exact: true })).toBeVisible()
})
