import { expect, test } from '@playwright/test'

const password = 'correct horse battery staple'

test('generic inventory workflow supports duplicate copies and location states', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Username').fill('adminuser')
  await page.getByLabel('Password').fill(password)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByLabel('Open application menu')).toBeVisible()
  await page.goto('/collections')
  await page.getByRole('link', { name: 'Browser collection' }).click()
  const collectionPath = new URL(page.url()).pathname
  const collectionId = collectionPath.split('/').at(-2)

  await page.goto(`/collections/${collectionId}/inventory`)
  const collectionNavigation = page.getByLabel('Collection navigation')
  await expect(collectionNavigation.getByRole('link')).toHaveText(['Inventory', 'Locations', 'Settings'])
  await collectionNavigation.getByRole('link', { name: 'Settings' }).click()
  await page.getByRole('button', { name: 'Advanced' }).click()
  await page.getByRole('link', { name: 'Open advanced catalog' }).click()
  await expect(page.getByRole('heading', { name: 'Advanced catalog' })).toBeVisible()
  await page.goto(`/collections/${collectionId}/inventory`)
  await page.getByRole('link', { name: 'Add item' }).click()
  await page.getByLabel('Title').fill('T06 Browser Title')
  await page.getByRole('button', { name: 'Create new title "T06 Browser Title"' }).click()
  await page.getByLabel('Edition name').fill('T06 Browser Edition')
  await page.getByLabel('Media format').fill('Blu-ray')
  await page.getByRole('button', { name: 'Add item' }).click()
  await expect(page.getByRole('heading', { name: 'T06 Browser Title' })).toBeVisible()
  await page.getByRole('link', { name: 'Back to Inventory' }).click()
  await page.getByRole('link', { name: 'Add item' }).click()
  await page.getByLabel('Title').fill('T06 Browser Title')
  await expect(page.getByRole('button', { name: 'Use existing' })).toBeVisible()
  await page.getByRole('button', { name: 'Use existing' }).click()
  await page.getByRole('button', { name: 'Use this edition' }).click()
  await page.getByRole('button', { name: 'Add item' }).click()
  await page.getByRole('link', { name: 'Back to Inventory' }).click()
  const titleCard = page.locator('.library-card').filter({ hasText: 'T06 Browser Title' })
  await expect(titleCard).toHaveCount(1)
  await expect(titleCard).toContainText('1 edition · 2 copies')
  await expect(page.locator('.filter-toolbar__summary')).toContainText('1 title · 2 physical copies')
  await titleCard.getByRole('link', { name: 'Open T06 Browser Title' }).click()

  const firstCopy = page.locator('.copy-read-card').filter({ hasText: 'Copy 1' })
  await firstCopy.getByRole('link', { name: 'Edit copy' }).click()
  await expect(page.getByRole('heading', { name: 'Copy 1' })).toBeVisible()
  await page.locator('.collection-form input').fill('Very good')
  await page.locator('.collection-form textarea').fill('Browser-managed copy')
  await page.getByRole('button', { name: 'Save copy' }).click()
  await expect(page.getByText('Very good')).toBeVisible()
  await expect(page.getByText('Browser-managed copy')).toBeVisible()

  await firstCopy.getByRole('link', { name: 'Edit copy' }).click()
  await page.getByRole('button', { name: 'Location' }).click()
  const currentLocation = page.locator('.copy-location-management__current')
  await expect(currentLocation).toContainText('Unassigned')
  await page.getByLabel('Move / Assign location').selectOption({ index: 1 })
  await page.getByRole('button', { name: 'Assign location' }).click()
  await expect(currentLocation).not.toContainText('Unassigned')
  await page.getByRole('button', { name: 'Remove from location' }).click()
  await expect(currentLocation).toContainText('Unassigned')
})
