<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiError } from '@/api/client'
import { useCatalogStore } from '@/stores/catalog'
import { useCollectionsStore } from '@/stores/collections'
const route=useRoute();const router=useRouter();const catalog=useCatalogStore();const collections=useCollectionsStore();const name=ref('');const title=ref('');const type=ref('');const sortTitle=ref('');const notes=ref('');const editing=ref(false);const editingEdition=ref<number|null>(null);const editionForm=ref({display_name:'',release_date:'',publisher:'',region:'',language:''});const confirming=ref(false);const error=ref('');const id=()=>Number(route.params.collectionId);const entryId=()=>Number(route.params.entryId);const canEdit=computed(()=>['owner','admin','editor'].includes(collections.collection?.role??''))
async function load(){await collections.loadCollection(id());await catalog.loadDetail(id(),entryId())}watch(()=>route.params.entryId,load,{immediate:true})
async function add(){await catalog.createEdition(id(),entryId(),{display_name:name.value});name.value='';await catalog.loadDetail(id(),entryId())}
function beginEditionEdit(edition:{id:number;display_name:string;release_date:string|null;publisher:string|null;region:string|null;language:string|null}){editingEdition.value=edition.id;editionForm.value={display_name:edition.display_name,release_date:edition.release_date??'',publisher:edition.publisher??'',region:edition.region??'',language:edition.language??''}}
function beginEdit(){if(!catalog.entry)return;title.value=catalog.entry.display_title;type.value=catalog.entry.type;sortTitle.value=catalog.entry.sort_title??'';notes.value=catalog.entry.notes??'';error.value='';editing.value=true}
function message(cause:unknown){if(cause instanceof ApiError){if(cause.status===403)return 'You do not have permission for this action.';if(cause.status===404)return 'This catalog entry is no longer available.';if(cause.status===409)return 'This change conflicts with existing data.';if(cause.status===422)return 'Check the entered catalog entry details.'}return 'This action could not be completed. Please try again.'}
async function save(){if(!title.value.trim()){error.value='Display title is required.';return}try{await catalog.updateCatalog(id(),entryId(),{display_title:title.value.trim(),type:type.value,sort_title:sortTitle.value.trim()||null,notes:notes.value.trim()||null});await catalog.loadDetail(id(),entryId());editing.value=false}catch(cause){error.value=message(cause)}}
async function remove(){try{await catalog.deleteCatalog(id(),entryId());await router.push({name:'catalog',params:{collectionId:id()}})}catch(cause){error.value=message(cause);confirming.value=false}}
</script>
<template><section class="page-content"><RouterLink :to="{name:'catalog',params:{collectionId:id()}}">← Catalog</RouterLink><p v-if="catalog.loading">Loading…</p><div v-else-if="catalog.entry"><h1>{{catalog.entry.display_title}}</h1><p>Type: {{catalog.entry.type}}</p><p v-if="catalog.entry.sort_title">Sort title: {{catalog.entry.sort_title}}</p><p v-if="catalog.entry.notes">{{catalog.entry.notes}}</p><div v-if="canEdit"><button @click="beginEdit">Edit entry</button><button class="button-danger" @click="confirming=true">Delete entry</button></div><form v-if="editing" @submit.prevent="save"><label>Display title<input v-model="title" required /></label><label>Type<input v-model="type" required /></label><label>Sort title<input v-model="sortTitle" /></label><label>Notes<textarea v-model="notes" /></label><button>Save</button><button type="button" @click="editing=false">Cancel</button></form><section v-if="confirming"><p>Deleting this catalog entry also removes all editions, identifiers and physical inventory copies belonging to it.</p><button class="button-danger" @click="remove">Confirm delete</button><button @click="confirming=false">Cancel</button></section><p v-if="error" class="form-error" role="alert">{{error}}</p><h2>Editions</h2><ul><li v-for="edition in catalog.editions" :key="edition.id">{{edition.display_name}}<span v-if="edition.release_date"> · {{edition.release_date}}</span><span v-if="edition.publisher"> · {{edition.publisher}}</span><span v-if="edition.region"> · {{edition.region}}</span><span v-if="edition.language"> · {{edition.language}}</span><button v-if="canEdit" @click="beginEditionEdit(edition)">Edit edition</button><form v-if="editingEdition===edition.id"><label>Display name<input v-model="editionForm.display_name" /></label><label>Release date<input v-model="editionForm.release_date" type="date" /></label><label>Publisher<input v-model="editionForm.publisher" /></label><label>Region<input v-model="editionForm.region" /></label><label>Language<input v-model="editionForm.language" /></label><button type="button" @click="editingEdition=null">Cancel</button></form></li></ul><form v-if="canEdit" @submit.prevent="add"><label>Edition name<input v-model="name" required /></label><button>Add edition</button></form></div></section></template>
