import { flushPromises, mount } from '@vue/test-utils'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter } from 'vue-router'
import { describe, expect, it, vi } from 'vitest'
import * as collectionsApi from '@/api/collections'
import * as libraryApi from '@/api/library'
import * as locationsApi from '@/api/locations'
import InventoryAddItemView from './InventoryAddItemView.vue'
vi.mock('@/api/collections'); vi.mock('@/api/library'); vi.mock('@/api/locations')
const router=createRouter({history:createMemoryHistory(),routes:[{path:'/collections/:collectionId/inventory/add',name:'inventory-add',component:InventoryAddItemView},{path:'/collections/:collectionId/inventory',name:'inventory',component:InventoryAddItemView},{path:'/collections/:collectionId/inventory/:catalogEntryId',name:'inventory-title',component:InventoryAddItemView}]})
const title={id:2,collection_id:1,display_title:'Alien',type:'movies',sort_title:null,notes:null}; const detail={catalog_entry:title,editions:[{id:3,catalog_entry_id:2,display_name:'Special Edition',media_format:'Blu-ray',release_date:null,publisher:null,region:null,language:null,identifiers:[],copies:[]}]}
async function view(role:'owner'|'editor'|'viewer'='editor'){vi.mocked(collectionsApi.getCollection).mockResolvedValue({...title,name:'Films',role,owner:{id:1,username:'owner',display_name:null}});vi.mocked(locationsApi.listLocationTree).mockResolvedValue([{id:7,collection_id:1,parent_id:null,name:'House',type:'room',description:null,children:[{id:8,collection_id:1,parent_id:7,name:'Shelf',type:'shelf',description:null,children:[]}]}]);vi.mocked(libraryApi.searchTitles).mockResolvedValue([{id:2,catalog_entry_id:2,display_title:'Alien',sort_title:null,type:'movies',edition_count:1,copy_count:0,media_formats:['Blu-ray']}]);vi.mocked(libraryApi.getLibraryTitle).mockResolvedValue(detail);await router.push('/collections/1/inventory/add');const w=mount(InventoryAddItemView,{global:{plugins:[createPinia(),router]}});await flushPromises();return w}
describe('InventoryAddItemView',()=>{it('keeps viewers read-only and starts progressively',async()=>{const viewer=await view('viewer');expect(viewer.text()).toContain('do not have permission');expect(viewer.find('form').exists()).toBe(false);const editor=await view();expect(editor.text()).toContain('Title');expect(editor.text()).not.toContain('Physical copy')});it('requires explicit title and edition choices before it submits',async()=>{const w=await view();const input=w.get('input');await input.setValue('Alien');await new Promise(r=>setTimeout(r,350));await flushPromises();expect(libraryApi.searchTitles).toHaveBeenCalledWith(1,'Alien');expect(w.text()).toContain('Use existing');expect(w.text()).not.toContain('Physical copy');await w.get('button').trigger('click');await flushPromises();expect(libraryApi.getLibraryTitle).toHaveBeenCalledWith(1,2);expect(w.text()).toContain('Use this edition');const use=w.findAll('button').find(b=>b.text()==='Use this edition')!;await use.trigger('click');expect(w.text()).toContain('Physical copy')})})
