import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { createPinia } from 'pinia'
import { createMemoryHistory, createRouter } from 'vue-router'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { ApiError } from '@/api/client'
import * as catalogApi from '@/api/catalog'
import * as collectionsApi from '@/api/collections'
import * as inventoryApi from '@/api/inventory'
import * as locationsApi from '@/api/locations'
import InventoryView from './InventoryView.vue'
vi.mock('@/api/catalog');vi.mock('@/api/collections');vi.mock('@/api/inventory');vi.mock('@/api/locations')
const router=createRouter({history:createMemoryHistory(),routes:[{path:'/collections/:collectionId',name:'collection-detail',component:InventoryView},{path:'/collections/:collectionId/inventory',name:'inventory',component:InventoryView}]})
const entry={id:2,collection_id:1,display_title:'Blade Runner',type:'movie',sort_title:null,notes:null};const edition={id:3,catalog_entry_id:2,display_name:'UHD Blu-ray',release_date:null,publisher:null,region:null,language:null};const first={id:4,edition_id:3,condition:'Good',notes:'Shelf copy',location_id:null,created_at:'2026-01-01T00:00:00',updated_at:'2026-01-01T00:00:00'};const second={...first,id:5,condition:null,notes:null,location_id:9}
const tree=[{id:7,collection_id:1,parent_id:null,name:'House',type:'room' as const,description:null,children:[{id:8,collection_id:1,parent_id:7,name:'Basement',type:'room' as const,description:null,children:[{id:9,collection_id:1,parent_id:8,name:'Box',type:'box' as const,description:null,children:[]}]}]}]
async function view(role:'owner'|'admin'|'editor'|'viewer'='owner',items=[first,second]){vi.mocked(collectionsApi.getCollection).mockResolvedValue({id:1,name:'Films',type:'movies',description:null,role,owner:{id:1,username:'owner',display_name:null}});vi.mocked(inventoryApi.listInventory).mockResolvedValue(items);vi.mocked(catalogApi.listCatalog).mockResolvedValue([entry]);vi.mocked(catalogApi.listEditions).mockResolvedValue([edition]);vi.mocked(locationsApi.listLocationTree).mockResolvedValue(tree);await router.push('/collections/1/inventory');const wrapper=mount(InventoryView,{global:{plugins:[createPinia(),router]}});await flushPromises();return wrapper}
function button(wrapper:VueWrapper,name:string){return wrapper.findAll('button').find(candidate=>candidate.text()===name)}
function input(wrapper:VueWrapper,label:string){const field=wrapper.findAll('label').find(candidate=>candidate.text().startsWith(label));if(!field)throw new Error(label);return field.get('input, textarea, select')}
function form(wrapper:VueWrapper,text:string){const found=wrapper.findAll('form').find(candidate=>candidate.text().includes(text));if(!found)throw new Error(text);return found}
afterEach(()=>vi.clearAllMocks())
describe('InventoryView',()=>{
 it('renders ordered copies with title, edition, metadata and location state',async()=>{const w=await view();expect(w.text()).toContain('Blade Runner');expect(w.text()).toContain('UHD Blu-ray');expect(w.text()).toContain('Good');expect(w.text()).toContain('Shelf copy');expect(w.text()).toContain('Unassigned');expect(w.text()).toContain('House > Basement > Box');expect(w.findAll('.inventory-list > li').map(item=>item.text())).toHaveLength(2)})
 it('shows role-aware empty state',async()=>{expect((await view('owner',[])).text()).toContain('Add physical copy');expect((await view('viewer',[])).text()).not.toContain('Add physical copy')})
 it.each(['owner','admin','editor'] as const)('%s can create, edit and delete copies',async role=>{const w=await view(role);expect(button(w,'Add physical copy')).toBeDefined();expect(button(w,'Edit copy')).toBeDefined();expect(button(w,'Delete copy')).toBeDefined()})
 it('keeps viewers read-only',async()=>{const w=await view('viewer');expect(button(w,'Add physical copy')).toBeUndefined();expect(button(w,'Edit copy')).toBeUndefined();expect(button(w,'Delete copy')).toBeUndefined()})
 it('creates unassigned copies of the same edition',async()=>{vi.mocked(inventoryApi.createInventoryItem).mockResolvedValue({...first,id:6,condition:null,notes:null});const w=await view();await button(w,'Add physical copy')?.trigger('click');expect(w.text()).toContain('Blade Runner — UHD Blu-ray');await input(w,'Edition').setValue('3');await form(w,'Create physical copy').trigger('submit');await flushPromises();expect(inventoryApi.createInventoryItem).toHaveBeenCalledWith(1,{edition_id:3,condition:null,notes:null});expect(w.findAll('.inventory-list > li')).toHaveLength(3)})
 it('creates copies with optional condition and notes',async()=>{vi.mocked(inventoryApi.createInventoryItem).mockResolvedValue({...first,id:6});const w=await view();await button(w,'Add physical copy')?.trigger('click');await input(w,'Edition').setValue('3');await input(w,'Condition').setValue('Excellent');await input(w,'Notes').setValue('Second copy');await form(w,'Create physical copy').trigger('submit');await flushPromises();expect(inventoryApi.createInventoryItem).toHaveBeenCalledWith(1,{edition_id:3,condition:'Excellent',notes:'Second copy'})})
 it('edits a copy with explicit null semantics',async()=>{vi.mocked(inventoryApi.updateInventoryItem).mockResolvedValue({...first,condition:null,notes:null});const w=await view();await button(w,'Edit copy')?.trigger('click');expect(input(w,'Condition').element.value).toBe('Good');await input(w,'Condition').setValue('');await input(w,'Notes').setValue('');await form(w,'Save copy').trigger('submit');await flushPromises();expect(inventoryApi.updateInventoryItem).toHaveBeenCalledWith(1,4,{condition:null,notes:null})})
 it('keeps a copy visible after update failure',async()=>{vi.mocked(inventoryApi.updateInventoryItem).mockRejectedValue(new ApiError(403));const w=await view();await button(w,'Edit copy')?.trigger('click');await form(w,'Save copy').trigger('submit');await flushPromises();expect(w.text()).toContain('Shelf copy');expect(w.get('[role="alert"]').text()).toContain('permission')})
 it('requires confirmation and deletes only the selected copy',async()=>{vi.mocked(inventoryApi.deleteInventoryItem).mockResolvedValue();const w=await view();await button(w,'Delete copy')?.trigger('click');expect(inventoryApi.deleteInventoryItem).not.toHaveBeenCalled();expect(w.text()).toContain('Delete this physical copy?');await button(w,'Confirm delete copy')?.trigger('click');await flushPromises();expect(inventoryApi.deleteInventoryItem).toHaveBeenCalledWith(1,4);expect(w.text()).toContain('House > Basement > Box');expect(w.text()).not.toContain('Shelf copy')})
 it('keeps a copy visible after delete failure',async()=>{vi.mocked(inventoryApi.deleteInventoryItem).mockRejectedValue(new ApiError(404));const w=await view();await button(w,'Delete copy')?.trigger('click');await button(w,'Confirm delete copy')?.trigger('click');await flushPromises();expect(w.text()).toContain('Shelf copy');expect(w.get('[role="alert"]').text()).toContain('no longer available')})
 it('renders nested location paths and lets editors assign a location',async()=>{vi.mocked(inventoryApi.updateInventoryItem).mockResolvedValue({...first,location_id:9});const w=await view('editor');expect(w.text()).toContain('House > Basement > Box');await button(w,'Assign location')?.trigger('click');await input(w,'Location').setValue('9');await form(w,'Save location').trigger('submit');await flushPromises();expect(inventoryApi.updateInventoryItem).toHaveBeenCalledWith(1,4,{location_id:9});expect(w.text()).toContain('House > Basement > Box')})
 it('moves and unassigns without optimistic state on error',async()=>{vi.mocked(inventoryApi.updateInventoryItem).mockResolvedValueOnce({...second,location_id:7}).mockResolvedValueOnce({...second,location_id:null});const w=await view();await button(w,'Change location')?.trigger('click');await input(w,'Location').setValue('7');await form(w,'Save location').trigger('submit');await flushPromises();expect(inventoryApi.updateInventoryItem).toHaveBeenLastCalledWith(1,5,{location_id:7});await button(w,'Remove location')?.trigger('click');await form(w,'Save location').trigger('submit');await flushPromises();expect(inventoryApi.updateInventoryItem).toHaveBeenLastCalledWith(1,5,{location_id:null});expect(w.text()).toContain('Unassigned')})
 it('passes all, unassigned, recursive and exact filters without stale parameters',async()=>{const w=await view('viewer');await form(w,'Apply filter').trigger('submit');await flushPromises();expect(inventoryApi.listInventory).toHaveBeenLastCalledWith(1,{});await input(w,'Filter').setValue('unassigned');await form(w,'Apply filter').trigger('submit');await flushPromises();expect(inventoryApi.listInventory).toHaveBeenLastCalledWith(1,{unassigned:true});await input(w,'Filter').setValue('location');await input(w,'Location').setValue('7');await form(w,'Apply filter').trigger('submit');await flushPromises();expect(inventoryApi.listInventory).toHaveBeenLastCalledWith(1,{locationId:7,includeDescendants:true});const checkbox=w.get('input[type="checkbox"]');await checkbox.setValue(false);await form(w,'Apply filter').trigger('submit');await flushPromises();expect(inventoryApi.listInventory).toHaveBeenLastCalledWith(1,{locationId:7,includeDescendants:false});expect(button(w,'Assign location')).toBeUndefined()})
 it('cancels copy editing without mutation or location changes',async()=>{const w=await view();await button(w,'Edit copy')?.trigger('click');await input(w,'Condition').setValue('Changed');await button(w,'Cancel')?.trigger('click');expect(inventoryApi.updateInventoryItem).not.toHaveBeenCalled();expect(w.text()).toContain('Good');expect(w.text()).toContain('House > Basement > Box')})
})
